development:
  host: localhost
  database: codebrawl_development

test:
  host: localhost
  database: codebrawl_test

# set these environment variables on your prod server
production:
  host: localhost
  database: codebrawl_production
